[package]
name = "automata-dcap-qpl-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
automata-dcap-network-registry = { git = "https://github.com/automata-network/automata-dcap-attestation.git", rev = "f71d6521cc30806da369c7ee609af47c02b73448" }
automata-dcap-qpl = { git = "https://github.com/automata-network/automata-dcap-attestation.git", rev = "f71d6521cc30806da369c7ee609af47c02b73448" }
clap = { version = "4.5", features = ["derive"] }
hex = "0.4.3"
