#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod ierc721_token_receiver;
pub mod mock_erc20;
pub mod mock_erc721;
pub mod moonblaze;
pub mod std_invariant;
pub mod std_style;
